.TH runescape "6" "October 2017" "RUNESCAPE" "Faces a war in a fantasy world"
.SH NAME
runescape \- offers players a huge variety of benefits such as hundreds of additional quests and adventures, a larger game world to explore, exclusive skills and master and access to a whole host of minigames.
.br
Players can also access the most powerful weaponry and armour in the game, create clan citadels with their friends and even build their very own house.
.br
.SH SYNOPSIS
.B runescape
.RI [ keyboard ]
.RI [ mouse ]
.RI [ author ]
.br
.SH KEYBOARD
.br
.B Keyboard - Short Keys
.br
=====================
.br
These short keys are often used in PvM and PvP, to quickly switch/access weapons, prayers, Inventory (potions, food, teleport) or Magic spells (Teleport, combat spells).
.PP
.B	KEY					ACTION
.br
F1:					Backpack inventory
.br
F2:					Worn Equipment
.br
F3:					Prayer screen
.br
F4:					Magic spell screen
.br
F5:					Combat screen
.br
F9:					Quick chat response menu
.br
F10:					Quick chat context menu
.br
F11:					Repeat last Quick chat message
.br
Home:				Return to main quick chat menu
.br
Page up/down:			Scroll through quick chat options
.br
Enter:				Select Quick chat option
.br
Esc:					Exit chat menu or delete typed message before sending
.br
Tab:					Reply to sender of last private message
.br
/:					Respond in Friends chat
.br
//:					Respond in Clan chat
.br
///:					Respond in guest clan chat 
.br
.PP
Additionally, the letters and numbers preceding each quick chat option can be pressed to quickly select them.
.br
.SH MOUSE
.br
.B Mouse Controls
.br
==============
.br
Most players use a mouse as their pointing device. This will include the ability to position an on-screen pointer and two (primary and secondary) buttons to perform actions.
.PP
.B Primary button (usually left)
.br
- On a character that can be attacked, usually of a higher level: Attack.
.br
- On an NPC: Talk to.
.br
- On an item in the inventory: Wear, wield, bury, eat, or "use with" if no other action applies.
.br
- On an item on the ground: Take the most expensive (in shop value) item from the pile.
.br
- In the bank, on the bank screen or inventory: Transfer one item.
.br
- Holding the "Control" (Ctrl) key with any mouse click target means the player will run to a location (if they have enough energy).
.br
.PP
.B Secondary button (usually right)
.br
- Pressing the secondary mouse button offers a list of all possible actions that players can perform, or options to deal with more than one item.
.br
- Players may have to right click if attempting to attack a monster with a higher combat level than it.
.br
- In the example above, left-click the raw fish, then right-click the spot containing the player and the fire and select "Use with fire" from the menu.
.br
- In the bank, players can avoid the usual dialogue with the banker by using the secondary click option "Use-quickly bank booth" or "Bank banker".
.br
- Another time players must right-click is when combining two food items that are both edible, and some other situations where they would otherwise eat or drink an item instead of handing it over.
.br
.SH AUTHOR
This script was created and written by Carlos Donizete Froes [a.k.a coringao].
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao], for the Debian project (but may be used by others).

