.\" BSD 2-Clause License
.\"
.\" Copyright (c) 2016-2018, Carlos Donizete Froes <coringao@riseup.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice,
.\"   this list of conditions and the following disclaimer.
.\"
.\" * Redistributions in binary form must reproduce the above copyright notice,
.\"   this list of conditions and the following disclaimer in the documentation
.\"   and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
.\" OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH runescape "6" "August 2018" "RUNESCAPE"
.SH NAME
runescape \- is a massively multiplayer online role-playing game. Start your
adventure, complete quests and win enormous treasures in a 3D world of magic
and monsters.
.br
.SH CONTROLS
.br
Game controls in Runescape are quite basic, being mostly mouse driven, with
occasional use of the keyboard.
.PP
.B MOUSE CLICK (PRIMARY)
.PP
Clicking the primary (normally left) mouse button results in the default action
for the situation.
.PP
A few examples:
.br
* On the main view or minimap (radar): Walk to the position.
.br
* On a character that can be attacked, and is not a red level: Attack the
character.
.br
* On an NPC: Talk to.
.br
* On an item in your inventory: Wear, wield or eat it, or "use with" if
no other action applies.
.br
* On an item on the ground: Take the most expensive (in shop value) item
from the pile.
.br
* In the bank, on the bank screen or inventory: Transfer one item.
.PP
If there are many characters or items in one spot, the default action may not
select the object you want, a particular example being someone standing in
a fire, when you try to cook fish.
.PP
.B MOUSE CLICK (SECONDARY)
.PP
Clicking the secondary (normally right) mouse button offers a list of
all possible targets that can be selected, or options to deal with more
than one item.
.br
In the example above, you would click the fish you have, then secondary click
the player and fire, choosing "use with fire".
.br
In the bank, you can avoid the usual dialog by using secondary click
and "use quickly".
.br
Another time you must secondary click, is when combining two food items which
are both edible, and a couple of other situations where you would otherwise eat
or drink an item instead of handing it over.
.br
If your mouse only has one button, you can set the Mouse Buttons option to One,
so that every mouse click will be treated as a secondary mouse click.
.br
.PP
.B KEYBOARD
.PP
Running:
.br
--------
.br
Holding the CTRL key with any mouse click target means you will run to it,
useful for running to take an item, or to escape. Running may also be selected
using a panel option, but all movement will be made at a run until walking
is selected again, or your run energy falls to zero.
.br
.PP
Camera panning:
.br
---------------
.br
The arrow keys are used to pan the main view and minimap, rotating or raising
and lowering the viewpoint, though if close to a hill, it may not be possible
to lower the viewpoint.
.br
The middle mouse button can also be used to pan, as well as moving
the mouse while having Alt and left-click held down.
.br
While it can be useful to see items on the main view by rotating the map,
holding the map centred north while trying to navigate is highly recommended,
as it is easy to forget the map angle and set off in completely
the wrong direction.
.br
.PP
.B NUMBERS
.PP
The keyboard is used to enter amounts, particularly of coins.
Using the 5, 10 or all options for other items is quicker,
even if you have less, or don't have room to carry all.
.br
.PP
.B CHAT
.PP
You have Public Chat, Private Chat, Clan Chat and Trade Chat.
.br
The keyboard can also be used for chat with other players.
.br
It is not used to talk to NPCs in the game, as any responses are selected from
a menu. You can use the spacebar instead of pressing "click here to continue",
and you can use a number key instead of selecting the response with your mouse.
.br
.SH AUTHOR
This script was created and written by Carlos Donizete Froes [a.k.a coringao].
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao],
for the Debian project (but may be used by others).
